### PR TITLE
feat: add optional wifi ap pw

### PR DESCRIPTION
**Pull request by docgalaxyblock**
I added a wifi ap pw option to the `substitutions`.
The default is your current state of no pw.

I added a warning comment that if the user forget the pw it is required to open up the device again.
Therefore I added the hint to use the `Setup code` you can find at the Minis backside as the ap pw.

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I doubt whether it is useful to put these kinds of optional things in the YAML config, this could cause problems if a user in the future flashes their onju voice via ESP web tools.

**Comment by docgalaxyblock** [comment]
@klaasnicolaas What scenario do you have in mind? Cause after my change the default is still no ap pw at all.

**Comment by klaasnicolaas** [comment]
My advice would be not to merge optional code, if users would like to use a AP password they can add and compile it themselves.

./Klaas

**Comment by docgalaxyblock** [comment]
@tetele What is your opinion?

My intention is to give users a hint regarding securing up their onju fallback ap.

**Comment by tetele** [comment]
AP password is very rarely needed and, if so, the user should probably go for a custom config. I agree with Klaas.

**Pull request closed without merging**
