### PR TITLE
added brightness atribute to volume change

### PR DESCRIPTION
**Pull request by BloodyHellcat**
added this atribute to handle led switch between listening, or general, and the volume show phase. Example Situation resolvment: Having the listen LED's sequence set to 0% that I don't have light in my bedroom for sleeping, but when chaning the Volume, no volume level is show. This resolved this issue for me.

### CODE REVIEW

**Comment by tetele** [comment]
I don't understand what this PR is supposed to fix. The top LEDs are not exposed to HA and can't be turned off except if you modify the config. If so, then why would you think that everyone benefits from the modification that fixes your issue?

**Comment by BloodyHellcat** [comment]
It's not the idea to expose the top LEDs to HA.

In general, when an individual sets up their device and copies that config to their ESPHome interface, they need to change some things, such as the key.

Once there, most people will look through and change some things additionally, such as the local wake word config, to choose which wake word is used.

The brightness settings are an interesting part here, as some people prefer different values in different rooms.

This is best left in the substitution where it is easily accessible.

But in my PR here it's just adding the missing brightness setting to the LED sequence part that was missing.

My explained situation is just an example.

Should I do an additional commit with the substitution example I talked about? Maybe this would clarify the usefulness.

**Comment by tetele** [comment]
Sorry for the delay. Yes, the brightness should probably be a substitution setting, but I am not sure that's the only place it should be used.

Are you sure that the custom [`show_volume` effect](https://github.com/tetele/onju-voice-satellite/blob/55e871eebe8a8ef75e0cdc0ea0eef8ca03b7ac46/esphome/onju-voice-microwakeword.yaml#L438) doesn't need to take this value into consideration as well?

**Comment by BloodyHellcat** [comment]
Yes, sure from the testing side as it changes brightness as intended and I don't see any misbehaviour.

No, from the coding side, as I didn't look into that part till now.

Give me some maybe days, then I'll look into that aswell and come back with an answer + make a substitution Suggestion commit.

**Comment by BloodyHellcat** [comment]
Got some intressting but wrong behaviour recently.
Dooing some testing before continuing this isolated tests with the brightness settings.

**Pull request closed without merging**
